// <auto-generated />
using System;
using HalaqatManagmentSystem_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalaqatManagmentSystem_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityType")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guardians", null, t =>
                        {
                            t.HasCheckConstraint("CK_Guardians_MaritalStatus", "[MaritalStatus] >= 0 AND [MaritalStatus] <= 2");
                        });
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Halaqa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Halaqat", (string)null);
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<Guid?>("GuardianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GuardianKinship")
                        .HasColumnType("int");

                    b.Property<int?>("HalaqaId")
                        .HasColumnType("int");

                    b.Property<int>("LastMemorizedSurah")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuranicNarration")
                        .HasColumnType("int");

                    b.Property<int>("SchoolGrade")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SerialNumber"), 1000L);

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.HasIndex("HalaqaId");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Students_GuardianKinship", "[GuardianKinship] >= 0 AND [GuardianKinship] <= 11");

                            t.HasCheckConstraint("CK_Students_LastMemorizedSurah", "[LastMemorizedSurah] >= 1 AND [LastMemorizedSurah] <= 114");

                            t.HasCheckConstraint("CK_Students_SchoolGrade", "[SchoolGrade] >= 0 AND [SchoolGrade] <= 11");
                        });
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.StudentAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("StudentId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("StudentAttendances", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentAttendances_Status", "[Status] >= 0 AND [Status] <= 4");
                        });
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.StudentHalaqaEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentEnrollments", (string)null);
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityType")
                        .HasColumnType("int");

                    b.Property<int>("LastMemorizedSurah")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuranicNarration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Teachers_LastMemorizedSurah", "[LastMemorizedSurah] >= 1 AND [LastMemorizedSurah] <= 114");
                        });
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.TeachingAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HalaqaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HalaqaId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachingAssignments", (string)null);
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Halaqa", b =>
                {
                    b.HasOne("HalaqatManagmentSystem_API.Entities.Teacher", "Teacher")
                        .WithMany("Halaqat")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Student", b =>
                {
                    b.HasOne("HalaqatManagmentSystem_API.Entities.Guardian", "Guardian")
                        .WithMany("Students")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HalaqatManagmentSystem_API.Entities.Halaqa", "Halaqa")
                        .WithMany("Students")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guardian");

                    b.Navigation("Halaqa");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.StudentAttendance", b =>
                {
                    b.HasOne("HalaqatManagmentSystem_API.Entities.Halaqa", "Halaqa")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HalaqatManagmentSystem_API.Entities.Student", "Student")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halaqa");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.StudentHalaqaEnrollment", b =>
                {
                    b.HasOne("HalaqatManagmentSystem_API.Entities.Halaqa", "Halaqa")
                        .WithMany("EnrollmentsHistories")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HalaqatManagmentSystem_API.Entities.Student", "Student")
                        .WithMany("EnrollmentsHistories")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halaqa");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.TeachingAssignment", b =>
                {
                    b.HasOne("HalaqatManagmentSystem_API.Entities.Halaqa", "Halaqa")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("HalaqaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HalaqatManagmentSystem_API.Entities.Teacher", "Teacher")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Halaqa");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Guardian", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Halaqa", b =>
                {
                    b.Navigation("EnrollmentsHistories");

                    b.Navigation("StudentAttendances");

                    b.Navigation("Students");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Student", b =>
                {
                    b.Navigation("EnrollmentsHistories");

                    b.Navigation("StudentAttendances");
                });

            modelBuilder.Entity("HalaqatManagmentSystem_API.Entities.Teacher", b =>
                {
                    b.Navigation("Halaqat");

                    b.Navigation("TeachingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
